/**
 * Cloudflare Pages catch-all SSR handler for TanStack Start.
 *
 * How this works:
 *  1. `npm run build` runs first → Vite outputs the SSR bundle to dist/server/index.js
 *  2. Cloudflare Pages then compiles this functions/ directory using Wrangler/esbuild
 *  3. At compile time, dist/server/index.js already exists → import resolves correctly
 *  4. The bundler follows all imports (including dist/server/assets/) and inlines them
 *
 * dist/server/index.js is the Cloudflare Workers-compatible SSR entry produced by
 * @cloudflare/vite-plugin. It default-exports { fetch } — a standard Workers handler.
 *
 * Cloudflare Pages Functions run on the same Workers runtime, so this is compatible.
 *
 * Routing: This [[path]].ts catch-all runs ONLY when no static asset matches the
 * request — Cloudflare Pages automatically serves static files from dist/client/ first.
 */

// @ts-expect-error — this import is resolved at build time from dist/server/index.js
// which is generated by `npm run build` before functions are compiled.
import server from "../dist/server/server.js";

export const onRequest: PagesFunction = async (context) => {
  return server.fetch(context.request, context.env);
};
